# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Docs

on:
  push:
    branches: [ "main" ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdoc cc-serializer
    - name: Install Module
      run: |
        pip install .
    - name: Generate Docs
      run: |
        pdoc --docformat google -o ./docs cc.scpi
    - name: Commit Docs
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "ADD: build new docs"
